x-redis-url: &redis-url "${MM_REDIS_URL:-redis://mm-redis:6379/0}"

services:
  mm-postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=membermatters
      - POSTGRES_PASSWORD=membermatters
      - POSTGRES_DB=membermatters
    #ports:
    #  - "5432:5432"
    volumes:
      - mm-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U membermatters"]
      interval: 30s
      timeout: 5s
      retries: 5

  # MemberMatters Redis
  mm-redis:
    image: redis
    restart: always
    depends_on:
      - mm-postgres

  # MemberMatters
  mm-webapp:
    image: "${MM_IMAGE:-membermatters/membermatters}"
    restart: always
    environment:
      MM_ENV: "${MM_ENV:-Production}"
      MM_SECRET_KEY: "${MM_SECRET_KEY}"
      MM_ALLOWED_HOSTS: "${MM_ALLOWED_HOSTS}"
      MM_USE_POSTGRES: True
      MM_REDIS_HOST: *redis-url
      # Set to a secure value in production using this snippet:
      # python -c "import secrets; print(secrets.token_urlsafe())"
      HEALTH_CHECK_SECRET: "${HEALTH_CHECK_SECRET:-dev}"
    ports:
      - "8000:8000"
    depends_on:
      - mm-postgres
      - mm-redis
    healthcheck:
      test: ["CMD", "python", "manage.py", "health_check", "health_check-node", "mm-webapp:8000"]
      interval: 30s
      timeout: 10s
    volumes:
      - /usr/app:/usr/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/app/django.log:/usr/src/logs/django.log

  mm-staging:
    image: ghcr.io/sudoroom/membermatters:staging
    build:
      dockerfile: docker/Dockerfile
      context: ..
    restart: always
    environment:
      MM_TIME_ZONE: America/Los_Angeles
      MM_ENV: "Production"
      MM_USE_POSTGRES: True
      POSTGRES_DB: staging
      POSTGRES_USER: staging
      POSTGRES_PASSWORD: staging
      MM_REDIS_HOST: "redis://mm-redis:6379/1"
    ports:
      - "8001:8000"
    depends_on:
      - mm-postgres
      - mm-redis
    healthcheck:
      test: ["CMD", "python", "manage.py", "health_check", "health_check-node", "mm-webapp:8000"]
      interval: 30s
      timeout: 10s
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/app/django-staging.log:/usr/src/logs/django.log

  # MemberMatters Celery Worker
  mm-celery-worker:
    image: "${MM_IMAGE:-membermatters/membermatters}"
    restart: always
    environment:
      MM_ENV: "${MM_ENV:-Production}"
      MM_SECRET_KEY: "${MM_SECRET_KEY}"
      MM_ALLOWED_HOSTS: "${MM_ALLOWED_HOSTS}"
      MM_USE_POSTGRES: True
      MM_RUN_MODE: "celery_worker"
      MM_REDIS_HOST: *redis-url
    depends_on:
      - mm-webapp
      - mm-redis

  # MemberMatters Celery Beat
  mm-celery-beat:
    image: "${MM_IMAGE:-membermatters/membermatters}"
    restart: always
    environment:
      MM_ENV: "${MM_ENV:-Production}"
      MM_SECRET_KEY: "${MM_SECRET_KEY}"
      MM_ALLOWED_HOSTS: "${MM_ALLOWED_HOSTS}"
      MM_USE_POSTGRES: True
      MM_RUN_MODE: "celery_beat"
      MM_REDIS_HOST: *redis-url
    depends_on:
      - mm-webapp
      - mm-celery-worker
      - mm-redis

  mm-celery-prom-exporter:
    image: danihodovic/celery-exporter
    restart: always
    environment:
      CE_BROKER_URL: *redis-url
    depends_on:
      - mm-celery-worker
      - mm-redis

volumes:
  mm-postgres-volume:
    driver: local
